---
- name: Satellite | Capsule Install | Set Installer TFTP Parameters
  set_fact:
    satellite_installer_tftp_parameters: >
      --foreman-proxy-tftp 'true'
      --foreman-proxy-tftp-servername '{{ ansible_fqdn }}'
  when: satellite_installer_enable_tftp | default(False)

- name: Satellite | Capsule Install | Set Installer Remote Execution SSH Parameters
  set_fact:
    satellite_installer_remote_execution_ssh_parameters: >
      --enable-foreman-proxy-plugin-remote-execution-ssh
  when: satellite_installer_enable_remote_execution_ssh | default(False)

- name: Satelllite | Caspule Install | Run Scenario
  command: >
    satellite-installer --scenario capsule
      --capsule-parent-fqdn '{{ satellite_fqdn }}'
      --foreman-proxy-register-in-foreman 'true'
      --foreman-proxy-foreman-base-url 'https://{{ satellite_fqdn }}'
      --foreman-proxy-trusted-hosts '{{ satellite_fqdn }}'
      --foreman-proxy-trusted-hosts '{{ ansible_fqdn }}'
      --foreman-proxy-oauth-consumer-key '{{ satellite_oauth_consumer_key }}'
      --foreman-proxy-oauth-consumer-secret '{{ satellite_oauth_consumer_secret }}'
      --capsule-pulp-oauth-secret '{{ satellite_pulp_oauth_secret }}'
      --capsule-certs-tar '{{ satellite_capsule_server_cert_archive }}'
      --capsule-puppet true
      --capsule-puppet-ca-proxy 'https://{{ satellite_fqdn }}'
      {{ satellite_installer_tftp_parameters | default('') }}
      {{ satellite_installer_remote_execution_ssh_parameters | default ('') }}

- name: Satelllite | Caspule Install | Enable Discovery
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - foreman-discovery-image
    - rubygem-smart_proxy_discovery
  register: satellite_installer_enable_discovery_result
  when: satellite_installer_enable_remote_discovery

- name: Satelllite | Caspule Install | Restart katello service
  command: katello-service restart
  when: satellite_installer_enable_remote_discovery and satellite_installer_enable_discovery_result is changed
